import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Header } from "@/app//components/header";
import { Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: "400",
});
const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Union Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
